### ISSUE TITLE
fix: Project Explorer

### ISSUE THREAD

**Issue by dhruvsol** [cubik-so/cubik#192]
The UI card shows images of contributors 
<img width="457" alt="Screenshot 2023-07-16 at 2 15 00 PM" src="https://github.com/cubik-so/cubik/assets/89624156/1863f4c9-25b2-43ec-81ec-49d905bf428d">

on mobile, we will not show it.
for desktop need to change the Prisma API to only send 3 images and the count

**Comment by ashutosh887** [comment]
Hey I would like to work on this @dhruvsol
