### ISSUE TITLE
UI: Project filters

### ISSUE THREAD

**Issue by irffanasiff** [cubik-so/cubik#198]
Change the previous filters to this 
![Screenshot 2023-07-19 at 4 48 32 PM](https://github.com/cubik-so/cubik/assets/74172466/6268f19d-672f-4429-a084-99af3cc01c86)

**Comment by arihantbansal** [comment]
I can take this up

**Comment by irffanasiff** [comment]
Sure go ahead with that:
How will this work:
- When selecting a category the category should be displayed on the top tags
- Fix the position so the searched categories are visible

![Screenshot 2023-07-19 at 4 51 45 PM](https://github.com/cubik-so/cubik/assets/74172466/37358e61-55a4-4363-9ba3-bbfad946b837)

> Most of the filtering happens in the backend, if you find any issue with anything do ping me or @dhruvsol in the discord or anywhere or you can comment here also, thanks for the help 🙂

**Comment by irffanasiff** [comment]
@arihantbansal are you working on this one

**Comment by arihantbansal** [comment]
@irffanasiff yes

**Comment by irffanasiff** [comment]
let me know if you have any issues in discord - we need to do it fast or else i will take it up
