### ISSUE TITLE
Username validation failing

### ISSUE THREAD

**Issue by irffanasiff** [cubik-so/cubik#30]
Username validation is not working backend is responding with same message on every username request if the username is valid or not the response is same

**Comment by dhruvsol** [comment]
<img width="177" alt="Screenshot 2023-04-22 at 12 00 05 PM" src="https://user-images.githubusercontent.com/89624156/233766964-b7e00fc5-c289-4f4b-8246-5ede50826a1d.png">
@irffanasiff  Last char is not updating in the API thats why the logic is failing all time 
probably issue with usestate running in async

**Comment by dhruvsol** [comment]
updated a fix in main @irffanasiff
