### ISSUE TITLE
fix: menu list UI needs

### ISSUE THREAD

**Issue by irffanasiff** [cubik-so/cubik#443]
Issues
- [ ] Menu items are not aligned properly
- [ ] Submenu is not styled properly
- [ ] Menu buttons or icon buttons are not squared 

I have listed all the issues with images here
https://www.figma.com/file/7PlZ4TT4W6nEGu2n8Q5xFw/Issues?type=design&node-id=124%3A37&mode=design&t=KgekWnJs9T2WM8PJ-1

**Comment by ArpitaGanatra** [comment]
@irffanasiff 
Regarding the 2nd point, the submenu is styled properly, we dont have proper icons for those. Last updated, someone was designing it again.

If i put proper icons, it looks perfect. 👇
<img width="518" alt="Screenshot 2023-12-26 at 10 21 28 AM" src="https://github.com/cubik-so/cubik/assets/35517007/5bf1a60a-520b-44fb-b8d2-4ba0055b4205">

**Comment by irffanasiff** [comment]
i was not talking about the icons but the shadows colors etc it looked completely different as you can see in the screenshot

**Comment by ArpitaGanatra** [comment]
@irffanasiff i have fixed those things in this PR. you need to check it once. Also i have given color names as in figma, so if it looks diff, we might have to import them again
