### ISSUE TITLE
New: Segment control version that does not change query params 

### ISSUE THREAD

**Issue by irffanasiff** [cubik-so/cubik#444]
the current version of Segment control changes the url query params. we need a version of segment control that does not do this to use for normal purpose like 
- list or grid view change
- filter graphs time, 1W, 1M, 1Y

for reference check vercel segment control
https://vercel.com/design/switch

Add Segment Control to the docs 
https://squares.cubik.so/components/disclosure/segment

**Comment by irffanasiff** [comment]
Create a docs like this to review the component
- default state should be there like in the vercel version
- then a link version should be there ( show that in the docs )

![Screenshot 2023-12-26 at 3 06 45 PM](https://github.com/cubik-so/cubik/assets/74172466/5e6de0c4-4b7f-4cc5-ad5c-6027c14ca0f0)

**Comment by Dank-del** [comment]
@irffanasiff might wanna reassign dhruv for this one

**Comment by irffanasiff** [comment]
can you take it @Dank-del

**Comment by Dank-del** [comment]
> can you take it @Dank-del 

I actually don't understand it so I would prefer not to, would begin working on the other issue from tomorrow onwards

**Comment by irffanasiff** [comment]
can you talk to dhruv

**Comment by Dank-del** [comment]
> the current version of Segment control changes the url query params. we need a version of segment control that does not do this to use for normal purpose like 
> - list or grid view change
> - filter graphs time, 1W, 1M, 1Y
> 
> for reference check vercel segment control
> https://vercel.com/design/switch
> 
> Add Segment Control to the docs 
> https://squares.cubik.so/components/disclosure/segment

I really don't understand this

**Comment by Dank-del** [comment]
> can you talk to dhruv

Not today.

**Comment by Dank-del** [comment]
this one got resolved na? @dhruvsol

**Comment by dhruvsol** [comment]
Change is merged
